{ title: 'Phonat - Ride The Prejudice (Official Video)',
  description: null,
  summary: null,
  date: '2016-08-23T21:45:12.000Z',
  pubdate: '2013-06-24T19:09:30.000Z',
  pubDate: '2013-06-24T19:09:30.000Z',
  link: 'http://www.youtube.com/watch?v=xyZnIAU9yXw',
  guid: 'yt:video:xyZnIAU9yXw',
  author: 'OWSLA',
  comments: null,
  origlink: null,
  image: { url: 'https://i1.ytimg.com/vi/xyZnIAU9yXw/hqdefault.jpg' },
  source: {},
  categories: [],
  enclosures: [],
  'atom:@': {},
  'atom:id': { '@': {}, '#': 'yt:video:xyZnIAU9yXw' },
  'yt:videoid': { '@': {}, '#': 'xyZnIAU9yXw' },
  'yt:channelid': { '@': {}, '#': 'UC8nidfOKkcgpO6tfc9OSdBQ' },
  'atom:title': { '@': {}, '#': 'Phonat - Ride The Prejudice (Official Video)' },
  'atom:link':
   { '@':
      { rel: 'alternate',
        href: 'http://www.youtube.com/watch?v=xyZnIAU9yXw' } },
  'atom:author':
   { '@': {},
     name: { '@': {}, '#': 'OWSLA' },
     uri:
      { '@': {},
        '#': 'http://www.youtube.com/channel/UC8nidfOKkcgpO6tfc9OSdBQ' } },
  'atom:published': { '@': {}, '#': '2013-06-24T19:09:30+00:00' },
  'atom:updated': { '@': {}, '#': '2016-08-23T21:45:12+00:00' },
  'media:group':
   { '@': {},
     'media:title': { '@': {}, '#': 'Phonat - Ride The Prejudice (Official Video)' },
     'media:content': { '@': [Object] },
     'media:thumbnail': { '@': [Object] },
     'media:description':
      { '@': {},
        '#': 'OWSLA: owsla.com/releases/phonat-identity-theft-ep\nBeatport: beatport.com/release/identity-theft-ep/1090154\niTunes: smarturl.it/idtheft\n\nLike Phonat: http://facebook.com/phonat\nFollow Phonat: https://twitter.com/phonat\nListen to Phonat: https://soundcloud.com/phonat\nMore on Phonat: http://phonat.net' },
     'media:community':
      { '@': {},
        'media:starrating': [Object],
        'media:statistics': [Object] } },
  meta:
   { '#ns': [ [Object], [Object], [Object] ],
     '@': [ [Object], [Object], [Object] ],
     '#xml': { version: '1.0', encoding: 'UTF-8' },
     '#type': 'atom',
     '#version': '1.0',
     title: 'Cool Visuals',
     description: null,
     date: '2013-08-20T22:04:59.000Z',
     pubdate: '2013-08-20T22:04:59.000Z',
     pubDate: '2013-08-20T22:04:59.000Z',
     link: null,
     xmlurl: 'http://www.youtube.com/feeds/videos.xml?playlist_id=PL7_Q_mRk-hW8ZNRqnrUEzieoIUJ3MhO6a',
     xmlUrl: 'http://www.youtube.com/feeds/videos.xml?playlist_id=PL7_Q_mRk-hW8ZNRqnrUEzieoIUJ3MhO6a',
     author: 'Robben Fenderson',
     language: null,
     favicon: null,
     copyright: null,
     generator: null,
     cloud: {},
     image: {},
     categories: [],
     'atom:@':
      { 'xmlns:yt': 'http://www.youtube.com/xml/schemas/2015',
        'xmlns:media': 'http://search.yahoo.com/mrss/',
        xmlns: 'http://www.w3.org/2005/Atom' },
     'atom:link': { '@': [Object] },
     'atom:id':
      { '@': {},
        '#': 'yt:playlist:PL7_Q_mRk-hW8ZNRqnrUEzieoIUJ3MhO6a' },
     'yt:playlistid': { '@': {}, '#': 'PL7_Q_mRk-hW8ZNRqnrUEzieoIUJ3MhO6a' },
     'yt:channelid': { '@': {}, '#': 'UCI7TIe2Q8utWZdavVvFhrOA' },
     'atom:title': { '@': {}, '#': 'Cool Visuals' },
     'atom:author': { '@': {}, name: [Object], uri: [Object] },
     'atom:published': { '@': {}, '#': '2013-08-20T22:04:59+00:00' } } }
